import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import ReduxProvider from "./store/ReduxProvider";
import ProvidersRQ from "../context/QueryContext";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spend Smart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        layout: {
          logoImageUrl: "http://localhost:3000/logo.png",
          logoPlacement: "inside",
        },
      }}
    >
      <ReduxProvider>
        <ProvidersRQ>
        <html lang="en">
          <body className={roboto.className}>{children}</body>
        </html>
        </ProvidersRQ>
      </ReduxProvider>
    </ClerkProvider>
  );
}
